### PR TITLE
Feat/album api and more

### PR DESCRIPTION
**Pull request by RSNara**
This PR: 
- Implements the `/users/me/album` route
- Replaces [mocha](https://mochajs.org/) with [ava](https://github.com/avajs/ava)
- "Replaces" [sinon](http://sinonjs.org/) with [testdouble](https://github.com/testdouble/testdouble.js)
- Restructures the font-end to have a Navigation bar with a Login button that appears only if you're not logged in. Also did a bit of refactoring.
- Lowers all coverage requirements to 80%, because not everything needs to be tested. 
- Excludes configuration files from the coverage reports, because those files don't include business logic.
- Switches to [redux-actions](https://github.com/acdlite/redux-actions) for more terse action creators and reducers.
#### Reasons for AVA

Concurrent test execution by default. This encourages us to write tests not relying on shared global state. This means no more `beforeEach` or `afterEach` (well, not in the tests I've written anyway).  Also, tests should now execute much faster than they did before.
#### Resons for Testdouble

Better node `require` call mocking. But I'm not married to Testdouble, which is why I haven't removed sinon from the dependencies list. Also, Testdouble doesn't let you mock "anything you don't own", which can get annoying. This was necessary in some cases, so I included [proxyquire](https://github.com/thlorenz/proxyquire) as a `dev-dependency`.

@mandishshah and @Bbowen100 have fun reviewing these tests and changes.

Our tests now require `mongodb` to be installed locally. This might break our CI setup. Sigh...
#### Coverage Summary

screen shot 2016-07-02 at 12 44 32 am

Yeah... should have broken this PR up, but oh well.

### CODE REVIEW

**Comment by RSNara** [comment]
Yeah, we need `mongodb` installed. I'll try to get it enabled.

**Comment by RSNara** [comment]
Yeah... mongo is fine. Now our secrets file is the problem. I'll look into this later today.

**Comment by RSNara** [comment]
Uhhh... not accurate coverage.

**Comment by mandishshah** [comment]
So many changes LOL. Might have to move to CircleCi. Apparently Travis doesn't understand that this PR was created from a different remote than `boxal/boxal` -.-

I am assuming this stuff is working so :shipit:

**Pull request merged**
