### PR TITLE
Feat/album list

### PR DESCRIPTION
**Pull request by Bbowen100**

### CODE REVIEW

**Comment by mandishshah** [comment]
This needs to be rebased

**Comment by Bbowen100** [comment]
Not sure what these checks are, so Im gonna leave it to you guys to merge if its ok

**Comment by mandishshah** [comment]
I think these are mainly linting issues

**Comment by mandishshah** [comment]
Did you fix the linting issues?

**Comment by mandishshah** [comment]
Master build is broken https://travis-ci.org/boxal/boxal/builds/141374723

**Pull request merged**
